name = "Locke Data"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Theme for itsalocke.com"
homepage = "https://itsalocke.com"
tags = ["single page","Company","blog"]
features = []
min_version = "0.41"
depends_on = ["hugo-utilitybelt"]

[author]
  name = "Steph Locke"
  homepage = "https://itsalocke.com"
