theme = ["hugo-itsalocked", "hugo-utilitybelt"]

baseURL = "/"
languageCode = "en-gb"
title = "Locke Data"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableGitInfo = true

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]
  page = ["HTML", "AMP", "JSON"]

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
  talk = "talks"

[[menu.main]]
    name = "Authors"
    url = "/authors/"
[[menu.main]]
    name = "Talks"
    url = "/talks/"
[[menu.main]]
    name = "Products"
    url = "/products/"

[[menu.footer]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/cboettig"
    weight = 1
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/cboettig"
    weight = 2
[[menu.footer]]
    identifier = "copyright"
    name = "MIT"
    pre = "<i class='fa fa-balance-scale'></i>"
    url = "https://spdx.org/licenses/MIT"
    weight = 3


[params]
    custom_css = []
    custom_js = []
    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for staticman
    staticman_debug = true
    staticman_url = "https://api.staticman.net/v2/entry/lockedatapublished/itsalockev2/master/comments"
    
    # options for snipcart
    snipcart_test_api_key = "MTZiMjAxYzctNTFkNS00ZjFjLWI4YTAtZjU5OWQzNTc1YTZhNjM2NzAxOTY2OTQxMTUxNzkz"
    snipcart_live_api_key = "MTZiMjAxYzctNTFkNS00ZjFjLWI4YTAtZjU5OWQzNTc1YTZhNjM2NzAxOTY2OTQxMTUxNzkz"
    currency = "GBP"
    cloudinary_base_url = "https://res.cloudinary.com/dwalkr"
