[build]
  publish = "public"
  command =  "./build.sh"

[context.production.environment]
  HUGO_VERSION = "0.46"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.46"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.46"

[context.deploy-preview]
command = "./build.sh"

[context.branch-deploy]
command = "./build.sh"