[build]
  publish = "public"
  command =  "hugo && gulp"

[context.production.environment]
  HUGO_VERSION = "0.46"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.46"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.46"

[context.deploy-preview]
command = "chmod 777 build.sh && ./build.sh"

[context.branch-deploy]
command = "chmod 777 build.sh && ./build.sh"