[build]
  publish = "public"
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.production.environment]
  HUGO_VERSION = "0.42"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.42"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.42"