[build]
  publish = "public"
  command =  "hugo && gulp"

[context.production.environment]
  HUGO_VERSION = "0.50"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.50"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.50"

[context.deploy-preview]
command =  "hugo -b $DEPLOY_PRIME_URL && gulp"

[context.branch-deploy]
command =  "hugo -b $DEPLOY_PRIME_URL && gulp"
